trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - powershell: .\build.ps1

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'WinForms'
      targetPath: 'artifacts/WinForms'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Wpf'
      targetPath: 'artifacts/Wpf'

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: ./build.sh

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Gtk'
      targetPath: 'artifacts/Gtk'

- job: macOS
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - bash: 'pip install dmgbuild'

  - bash: ./build.sh

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Mac'
      targetPath: 'artifacts/Mac'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'XamMac'
      targetPath: 'artifacts/XamMac'
