trigger:
- master

variables:
  releasePlatformWindows: 'WinForms' # WinForms, Wpf
  releasePlatformLinux: 'Gtk' # Gtk
  releasePlatformMacOS: 'XamMac' # Mac, XamMac

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - powershell: .\build.ps1

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: '$(releasePlatformWindows)'
      targetPath: 'artifacts/$(releasePlatformWindows)'

# - job: Linux
#   pool:
#     vmImage: 'ubuntu-16.04'
#
#   steps:
#   - bash: ./build.sh
#
#   - task: PublishPipelineArtifact@0
#     inputs:
#       artifactName: '$(releasePlatformLinux)'
#       targetPath: 'artifacts/$(releasePlatformLinux)'

- job: macOS
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - bash: 'pip install dmgbuild'

  - bash: ./build.sh

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'macOSPackage'
      targetPath: 'artifacts/$(releasePlatformMacOS)'
