trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: PowerShell@2
    displayName: "Build"
    inputs:
      script: build.ps1

  - task: PublishPipelineArtifact@0
    displayName: "Publish WinForms package"
    inputs:
      artifactName: 'WinForms'
      targetPath: 'artifacts/WinForms'

  - task: PublishPipelineArtifact@0
    displayName: "Publish Wpf package"
    inputs:
      artifactName: 'Wpf'
      targetPath: 'artifacts/Wpf'

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: Bash@3
    displayName: "Build"
    inputs:
      script: build.sh

  - task: PublishPipelineArtifact@0
    displayName: "Publish Gtk package"
    inputs:
      artifactName: 'Gtk'
      targetPath: 'artifacts/Gtk'

- job: macOS
  pool:
    vmImage: 'macOS-10.14'

  steps:

  # Taken from https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  - task: Bash@3
    displayName: "Set Mono version"
    inputs:
      targetType: 'inline'
      script: |
        SYMLINK=5_18_1
        MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
        echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
        echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
        echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"

  - task: Bash@3
    displayName: "Install dmgbuild"
    inputs:
      script: 'pip install dmgbuild'

  - task: Bash@3
    displayName: "Build"
    inputs:
      script: build.sh

  - task: PublishPipelineArtifact@0
    displayName: "Publish Mac package"
    inputs:
      artifactName: 'Mac'
      targetPath: 'artifacts/Mac'

  - task: PublishPipelineArtifact@0
    displayName: "Publish XamMac package"
    inputs:
      artifactName: 'XamMac'
      targetPath: 'artifacts/XamMac'
