trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: "Get .NET Core 3.1 SDK"
    inputs:
      packageType: sdk
      version: 3.1.x

  - task: PowerShell@2
    displayName: "Build"
    inputs:
      filePath: build.ps1

  - task: PublishPipelineArtifact@0
    displayName: "Publish WinForms package"
    inputs:
      artifactName: 'WinForms'
      targetPath: 'artifacts/WinForms'

  - task: PublishPipelineArtifact@0
    displayName: "Publish Wpf package"
    inputs:
      artifactName: 'Wpf'
      targetPath: 'artifacts/Wpf'

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseDotNet@2
    displayName: "Get .NET Core 3.1 SDK"
    inputs:
      packageType: sdk
      version: 3.1.x

  - task: Bash@3
    displayName: "Build"
    inputs:
      filePath: build.sh

  - task: PublishPipelineArtifact@0
    displayName: "Publish Gtk package"
    inputs:
      artifactName: 'Gtk'
      targetPath: 'artifacts/Gtk'

- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - task: UseDotNet@2
    displayName: "Get .NET Core 3.1 SDK"
    inputs:
      packageType: sdk
      version: 3.1.x

  - task: Bash@3
    displayName: "Install dmgbuild"
    inputs:
      targetType: inline
      script: 'pip install dmgbuild'

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  - task: Bash@3
    displayName: "Select Xamarin SDK"
    inputs:
      targetType: inline
      script: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_18_1'

  - task: Bash@3
    displayName: "Build"
    inputs:
      filePath: build.sh

  - task: PublishPipelineArtifact@0
    displayName: "Publish Mac package"
    inputs:
      artifactName: 'Mac'
      targetPath: 'artifacts/Mac'

  - task: PublishPipelineArtifact@0
    displayName: "Publish XamMac package"
    inputs:
      artifactName: 'XamMac'
      targetPath: 'artifacts/XamMac'
