trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: PowerShell@2
    displayName: "Build"
    inputs:
      filePath: build.ps1

  - task: PublishPipelineArtifact@0
    displayName: "Publish WinForms package"
    inputs:
      artifactName: 'WinForms'
      targetPath: 'artifacts/WinForms'

  - task: PublishPipelineArtifact@0
    displayName: "Publish Wpf package"
    inputs:
      artifactName: 'Wpf'
      targetPath: 'artifacts/Wpf'

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Bash@3
    displayName: "Install gtk-sharp2"
    inputs:
      script: 'sudo apt-get install gtk-sharp2'

  - task: Bash@3
    displayName: "Build"
    inputs:
      filePath: build.sh

  - task: PublishPipelineArtifact@0
    displayName: "Publish Gtk2 package"
    inputs:
      artifactName: 'Gtk2'
      targetPath: 'artifacts/Gtk2'

- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - task: Bash@3
    displayName: "Install dmgbuild"
    inputs:
      targetType: inline
      script: 'pip3 install dmgbuild'

  - task: Bash@3
    displayName: "Build"
    inputs:
      filePath: build.sh

  - task: PublishPipelineArtifact@0
    displayName: "Publish Mac64 package"
    inputs:
      artifactName: 'Mac64'
      targetPath: 'artifacts/Mac64'
